name: Django CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create test settings
        run: |
          cd SMA
          echo "from SMA.settings import *" > test_settings.py
          echo "DATABASES = {" >> test_settings.py
          echo "    'default': {" >> test_settings.py
          echo "        'ENGINE': 'django.db.backends.sqlite3'," >> test_settings.py
          echo "        'NAME': ':memory:'," >> test_settings.py
          echo "    }" >> test_settings.py
          echo "}" >> test_settings.py
      - name: Run tests with pytest
        run: |
          cd SMA
          DJANGO_SETTINGS_MODULE=SMA.test_settings pytest plan/tests/test_utils.py -v